name: UtilityHats
main: pgDev.bukkit.UtilityHats.UtilityHats
version: 1.0
author: PG Dev Team
authors: [Devil Boy]
description: More hats, more dynamics!

commands:
   hat:
      description: Place a hat on your head.
      usage: /<command>
   uhat:
      description: Place a hat on your head.
      usage: /<command>
   utilityhat:
      description: Place a hat on your head.
      usage: /<command>

permissions:
    utilityhats.*:
        default: op
        description: Can use any hat.
        children:
            UtilityHats.book: true
            UtilityHats.glowstone: true
            UtilityHats.glass: true
            UtilityHats.spawner: true
            UtilityHats.obsidian: true
    utilityhats.book:
        default: true
        description: Can receive the help output.
    utilityhats.glowstone:
        default: true
        description: Can wear glowstone on head.
    utilityhats.glass:
        default: true
        description: Can wear glass on head.
    utilityhats.spawner:
        default: true
        description: Can wear a spawner on head.
    utilityhats.obsidian:
        default: true
        description: Can wear obsidian on head.
    utilityhats.piston:
        default: true
        description: Can wear piston on head.
    utilityhats.snow:
        default: true
        description: Can wear snow on head.